### ISSUE TITLE
thousandSeparator issue

### ISSUE THREAD

**Issue by i-akiya** [spilikin/SwiftXMLTools#2]
Hi there,

I import SwiftXMLTools v0.4 to my project by using XCode Version 11.3 (11C29), however I found the "Value of type 'NumberFormatter' has no member 'thousandSeparator'" error.

![スクリーンショット 2019-12-22 17 59 22](https://user-images.githubusercontent.com/4584549/71319722-43185400-24e5-11ea-8bd2-025c55a60cdd.png)

**Comment by spilikin** [comment]
Hi,

it seems there was an issue with iOS. I pushed 0.5.0, it should work now

**Comment by i-akiya** [comment]
Thanks,
That is great, I found no error in case of v0.5.0.
